site_name: MKDocs Site Template
theme: readthedocs
repo_url: http://github.com/gpduck/MKDocsSiteTemplate/
repo_name: GitHub
edit_uri: edit/MKDocsSiteTemplate/docs/
extra_css:
    - theme_dir/css/codehilite.css
markdown_extensions:
    - pymdownx.superfences
    - meta
    - toc
    - codehilite:
        guess_lang: false
    - admonition
